package com.madlava.api;

import com.madlava.reporting.AsciiTableRenderer;
import com.madlava.reporting.Json;
import java.time.Instant;
import java.util.*;

/** Human-readable diagnostic report facade; rendering is independent of Spark. */
public final class MadLavaReport {
    private MadLavaReport() { }
    public static String reportText() { return render(MadLavaStatistics.snapshotMap(), ReportTrigger.MANUAL, StatisticsMode.CUMULATIVE, ""); }
    public static String reportSinceText(String checkpointId) { return render(MadLavaStatistics.sinceMap(checkpointId), ReportTrigger.MANUAL, StatisticsMode.CHECKPOINT_DELTA, checkpointId); }
    public static String reportMarkdown() { return "```text\n"+reportText()+"```\n"; }
    public static String reportSinceMarkdown(String checkpointId) { return "```text\n"+reportSinceText(checkpointId)+"```\n"; }
    public static String scopeReportText(String resultId) { MadLavaScopes.ScopeResult r=MadLavaScopes.result(resultId); if(r==null)return "ERROR: UNKNOWN_OR_EXPIRED_SCOPE_RESULT\n"; String report=render(r.statistics,ReportTrigger.SCOPE_END,StatisticsMode.SCOPE_DELTA,r.scopeName()); int at=report.indexOf('\n',report.indexOf("Generated At:")); String metadata="Scope: "+r.scopeName()+"\nScope ID: "+r.scopeId()+"\nResult ID: "+resultId+"\nDuration Nanos: "+r.durationNanos()+"\n"; return at<0?report+metadata:report.substring(0,at+1)+metadata+report.substring(at+1); }
    public static String scopeReportMarkdown(String resultId) { return "```text\n"+scopeReportText(resultId)+"```\n"; }
    private static String render(Map<String,Object> snapshot,ReportTrigger trigger,StatisticsMode mode,String checkpoint){StringBuilder out=new StringBuilder("MadLava Runtime Report\n");out.append("Trigger: ").append(trigger).append("\nStatistics Mode: ").append(mode).append("\nGenerated At: ").append(Instant.now()).append("\n");if(!checkpoint.isEmpty())out.append("Checkpoint: ").append(checkpoint).append('\n');if("ERROR".equals(snapshot.get("status")))return out.append("ERROR: ").append(snapshot.get("reason")).append('\n').toString();metadata(out,snapshot,"schemaVersion","Schema Version");metadata(out,snapshot,"agentVersion","Agent Version");metadata(out,snapshot,"configurationVersion","Configuration Version");metadata(out,snapshot,"pid","JVM PID");Object features=snapshot.get("features");if(features instanceof Map<?,?>){Map<?,?> f=(Map<?,?>)features;renderMethod(out,f.get("methodProfiling"));renderSerialization(out,f.get("sparkSerialization"));}return out.toString();}
    private static void metadata(StringBuilder out,Map<String,Object> snapshot,String key,String label){if(snapshot.containsKey(key))out.append(label).append(": ").append(snapshot.get(key)).append('\n');}
    private static void renderMethod(StringBuilder out,Object value){if(!(value instanceof Map<?,?>))return;Map<?,?> section=(Map<?,?>)value;Object methods=section.get("methods");if(!(methods instanceof List<?>))return;List<List<String>> rows=new ArrayList<>();for(Object item:(List<?>)methods)if(item instanceof Map<?,?>){Map<?,?> m=(Map<?,?>)item;rows.add(List.of(String.valueOf(m.get("owner"))+"."+m.get("method"),String.format("%,d",number(m.get("invocations"))),String.format("%,d",number(m.get("totalDurationNanos")))));}out.append("\nMethod Profiling\n").append(AsciiTableRenderer.render(List.of("METHOD","INVOCATIONS","TOTAL NANOS"),rows,50,100));for(Object item:(List<?>)methods)if(item instanceof Map<?,?>){Map<?,?> m=(Map<?,?>)item;Object groups=m.get("argumentGroups");if(groups instanceof List<?>&&!((List<?>)groups).isEmpty()){List<List<String>> groupRows=new ArrayList<>();for(Object g:(List<?>)groups)if(g instanceof Map<?,?>){Map<?,?> gm=(Map<?,?>)g;groupRows.add(List.of(String.valueOf(gm.get("arguments")),String.format("%,d",number(gm.get("invocations")))));}out.append("\n").append(m.get("method")).append(" — Argument Groups\n").append(AsciiTableRenderer.render(List.of("ARGUMENTS","INVOCATIONS"),groupRows,50,100));}if(number(section.get("overflowArgumentInvocations"))>0)out.append("WARNING: ").append(number(section.get("overflowArgumentInvocations"))).append(" argument-group invocations overflowed the configured limit\n");}}
    private static void renderSerialization(StringBuilder out,Object value){if(!(value instanceof Map<?,?>))return;Object groups=((Map<?,?>)value).get("groups");if(!(groups instanceof List<?>))return;List<List<String>> rows=new ArrayList<>();for(Object item:(List<?>)groups)if(item instanceof Map<?,?>){Map<?,?> g=(Map<?,?>)item;rows.add(List.of(String.valueOf(g.get("implementation")),String.valueOf(g.get("layer")),String.valueOf(g.get("operation")),String.format("%,d",number(g.get("operations")))));}out.append("\nSpark Serialization\n").append(AsciiTableRenderer.render(List.of("IMPLEMENTATION","LAYER","OPERATION","CALLS"),rows,50,100));}
    private static long number(Object value){return value instanceof Number?((Number)value).longValue():0;}
}
