"use strict";
const $=id=>document.getElementById(id),input=$("report-file"),statusNode=$("status"),dashboard=$("dashboard"),selector=$("snapshot-select"),filter=$("feature-filter");
let report=[],sourceName="report.jsonl";
input.addEventListener("change",async()=>{const file=input.files&&input.files[0];if(!file)return;sourceName=file.name;statusNode.textContent=`Reading ${file.name}...`;try{report=parse(await file.text());populateSnapshots();render(report.length-1);dashboard.hidden=false;statusNode.textContent=`Loaded ${report.length} snapshot(s) from ${file.name}.`;}catch(error){report=[];dashboard.hidden=true;statusNode.textContent=error instanceof Error?error.message:"Unable to read report.";}});
selector.addEventListener("change",()=>render(Number(selector.value)));
filter.addEventListener("input",()=>renderFeatures(selected()));
$("export-summary").addEventListener("click",()=>{const value=selected(),blob=new Blob([JSON.stringify(summary(value),null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=sourceName.replace(/\.(jsonl|json)$/i,"")+"-summary.json";link.click();URL.revokeObjectURL(link.href);});
function parse(text){const lines=text.split(/\r?\n/).filter(line=>line.trim());if(!lines.length)throw new Error("The report is empty.");return lines.map((line,index)=>{let value;try{value=JSON.parse(line);}catch(ignored){throw new Error(`Malformed JSON on line ${index+1}.`);}if(!value||value.schemaVersion!==3)throw new Error(`Unsupported schema version on line ${index+1}.`);return value;});}
function populateSnapshots(){selector.replaceChildren();report.forEach((value,index)=>{const option=document.createElement("option");option.value=String(index);option.textContent=`#${value.snapshot&&value.snapshot.sequence||index+1}${value.snapshot&&value.snapshot.final?" (final)":""}`;selector.appendChild(option);});selector.value=String(report.length-1);}
function selected(){return report[Number(selector.value)||0];}
function render(index){selector.value=String(index);const value=report[index],snap=value.snapshot||{};$("snapshot-count").textContent=String(report.length);$("agent-version").textContent=String(value.agent&&value.agent.version||"unknown");$("last-sequence").textContent=String(snap.sequence||index+1);$("final-state").textContent=snap.final?"yes":"no";$("drop-count").textContent=String(snap.droppedSnapshots||value.droppedSnapshots||0);renderFeatures(value);renderDiagnostics(value);$("raw").textContent=JSON.stringify(value,null,2);}
function renderFeatures(value){const body=$("features"),needle=filter.value.trim().toLowerCase(),entries=Object.entries(value.features||{}).filter(([name,item])=>`${name} ${item&&item.state||""}`.toLowerCase().includes(needle));body.replaceChildren();let healthy=0;entries.forEach(([name,item])=>{item=item||{};const state=String(item.state||"UNAVAILABLE");if(state==="RUNNING"||state==="AVAILABLE")healthy++;const accuracy=item.accuracy&&item.accuracy.level||item.accuracy||"UNAVAILABLE",reason=item.reason||item.availability||item.limitations||"-",row=document.createElement("tr");row.dataset.state=state;[name,state,accuracy,reason].forEach(text=>{const cell=document.createElement("td");cell.textContent=String(text);row.appendChild(cell);});body.appendChild(row);});$("health-count").textContent=String(healthy);$("empty-features").hidden=entries.length!==0;}
function renderDiagnostics(value){const root=$("diagnostics");root.replaceChildren();const data=value.data||{},items=[];if(data.heapUsage)items.push(["Heap",formatBytes(data.heapUsage.used??data.heapUsage.usedBytes),formatBytes(data.heapUsage.max??data.heapUsage.maxBytes)]);if(data.threadStatistics)items.push(["Threads",data.threadStatistics.live??data.threadStatistics.threadCount??"-",`peak ${data.threadStatistics.peak??data.threadStatistics.peakThreadCount??"-"}`]);if(data.garbageCollection)items.push(["Garbage collection",data.garbageCollection.count??"-",`${data.garbageCollection.timeMillis??"-"} ms`]);if(data.spark)items.push(["Spark",data.spark.compatibility&&data.spark.compatibility.state||"UNAVAILABLE",data.spark.compatibility&&data.spark.compatibility.sparkVersion||"version unknown"]);if(!items.length)items.push(["Snapshot data","Available",`${Object.keys(data).length} data section(s)`]);items.forEach(parts=>{const card=document.createElement("article");parts.forEach((part,index)=>{const node=document.createElement(index===0?"h3":"p");node.textContent=String(part);card.appendChild(node);});root.appendChild(card);});}
function summary(value){return {source:sourceName,schemaVersion:value.schemaVersion,agent:value.agent,snapshot:value.snapshot,features:value.features,diagnosticSections:Object.keys(value.data||{})};}
function formatBytes(value){if(!Number.isFinite(Number(value)))return "-";const units=["B","KiB","MiB","GiB"];let n=Number(value),i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return `${n.toFixed(i?1:0)} ${units[i]}`;}
