"use strict";
const $=id=>document.getElementById(id),input=$("report-file"),directoryInput=$("report-directory"),statusNode=$("status"),dashboard=$("dashboard"),selector=$("snapshot-select"),filter=$("feature-filter");
let report=[],events=[],sourceName="report.jsonl";
input.addEventListener("change",async()=>{const files=orderReportFiles(Array.from(input.files||[]));if(!files.length)return;await loadReportFiles(files,files.length===1?files[0].name:`${files.length}-segment-run`,"Manual selection; integrity manifest not verified.");});
directoryInput.addEventListener("change",async()=>{const selectedFiles=Array.from(directoryInput.files||[]);if(!selectedFiles.length)return;statusNode.textContent="Discovering and verifying report run...";try{const discovered=await discoverRunFiles(selectedFiles);await loadReportFiles(discovered.files,discovered.name,discovered.integrity);}catch(error){clearReport(error);}});
selector.addEventListener("change",()=>render(Number(selector.value)));
filter.addEventListener("input",()=>renderFeatures(selected()));
$("export-summary").addEventListener("click",()=>{const value=selected(),blob=new Blob([JSON.stringify(summary(value),null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=sourceName.replace(/\.(jsonl|json)$/i,"")+"-summary.json";link.click();URL.revokeObjectURL(link.href);});
async function loadReportFiles(files,name,integrity){sourceName=name;statusNode.textContent=`Reading ${files.length} report segment(s)...`;try{const parsed=await parseFiles(files);report=parsed.snapshots;events=parsed.events;if(!report.length)throw new Error("The report contains no snapshots.");populateSnapshots();render(report.length-1);dashboard.hidden=false;statusNode.textContent=`Loaded ${report.length} snapshot(s) and ${events.length} event(s) from ${files.length} segment(s). ${integrity}`;}catch(error){clearReport(error);}}
function clearReport(error){report=[];events=[];dashboard.hidden=true;statusNode.textContent=error instanceof Error?error.message:"Unable to read report.";}
function relativePath(file){const raw=String(file.webkitRelativePath||file.name).replace(/\\/g,"/"),parts=raw.split("/").filter(Boolean);return parts.length>1?parts.slice(1).join("/"):(parts[0]||file.name);}
async function discoverRunFiles(files){const byPath=new Map(files.map(file=>[relativePath(file),file])),manifestFile=byPath.get("madlava-report-manifest.json");if(!manifestFile){const discovered=orderReportFiles(files.filter(file=>{const path=relativePath(file);return path==="madlava.jsonl"||/^segments\/segment-\d+\.jsonl$/i.test(path);}));if(!discovered.length)throw new Error("No MadLava JSONL files were found in the selected directory.");return {files:discovered,name:rootDirectoryName(files),integrity:"No FINAL manifest found; integrity not verified."};}let manifest;try{manifest=JSON.parse(await manifestFile.text());}catch(ignored){throw new Error("The MadLava report manifest is not valid JSON.");}if(manifest.state!=="FINAL")throw new Error("The selected run does not have a FINAL report manifest.");if(!Array.isArray(manifest.files)||!manifest.files.length)throw new Error("The report manifest has no per-file integrity metadata.");if(Number(manifest.segments)!==manifest.files.length)throw new Error("Manifest segment count does not match its file inventory.");const declared=[],seen=new Set();let totalBytes=0;for(const entry of manifest.files){const path=String(entry&&entry.path||"").replace(/\\/g,"/");if(!path||seen.has(path))throw new Error("Manifest contains an invalid or duplicate report path.");seen.add(path);const file=byPath.get(path);if(!file)throw new Error(`Manifest-declared report file is missing: ${path}.`);if(file.size!==Number(entry.bytes))throw new Error(`Size mismatch for ${path}.`);const actual=await sha256(file);if(actual!==String(entry.sha256||"").toLowerCase())throw new Error(`SHA-256 mismatch for ${path}.`);declared.push(file);totalBytes+=file.size;}if(totalBytes!==Number(manifest.bytes))throw new Error("Manifest total byte count does not match its file inventory.");return {files:orderReportFiles(declared),name:rootDirectoryName(files),integrity:"FINAL manifest file inventory, byte counts, and SHA-256 hashes verified."};}
function rootDirectoryName(files){const raw=String(files[0]&&files[0].webkitRelativePath||"").replace(/\\/g,"/");return raw.split("/").filter(Boolean)[0]||"madlava-run";}
async function sha256(file){if(!globalThis.crypto||!crypto.subtle)throw new Error("SHA-256 verification is unavailable in this browser context.");const bytes=await file.arrayBuffer(),digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,"0")).join("");}
function orderReportFiles(files){return files.slice().sort((left,right)=>{const a=reportFileOrder(relativePath(left)),b=reportFileOrder(relativePath(right));if(a.group!==b.group)return a.group-b.group;if(a.index!==b.index)return a.index-b.index;return relativePath(left).localeCompare(relativePath(right));});}
function reportFileOrder(name){const base=String(name).replace(/^.*[\\/]/,"");const match=/^segment-(\d+)\.jsonl$/i.exec(base);if(match)return {group:0,index:Number(match[1])};if(/^madlava\.jsonl$/i.test(base))return {group:2,index:0};return {group:1,index:0};}
async function parseFiles(files){const snapshots=[],parsedEvents=[];for(const file of files){const parsed=parse(await file.text(),relativePath(file));snapshots.push(...parsed.snapshots);parsedEvents.push(...parsed.events);}return {snapshots,events:parsedEvents};}
function parse(text,source=sourceName){const lines=text.split(/\r?\n/).filter(line=>line.trim());if(!lines.length)throw new Error(`The report segment ${source} is empty.`);const snapshots=[],parsedEvents=[];lines.forEach((line,index)=>{let value;try{value=JSON.parse(line);}catch(ignored){throw new Error(`Malformed JSON in ${source} on line ${index+1}.`);}const kind=recordType(value);if(kind==="snapshot"){if(![1,3,4].includes(value.schemaVersion))throw new Error(`Unsupported snapshot schema version in ${source} on line ${index+1}.`);snapshots.push(normalize(value));return;}if(kind==="method-trace"){if(value.schemaVersion!==5)throw new Error(`Unsupported method trace schema version in ${source} on line ${index+1}.`);parsedEvents.push(value);return;}if(kind==="configuration-change"){parsedEvents.push(value);return;}throw new Error(`Unsupported record type in ${source} on line ${index+1}.`);});return {snapshots,events:parsedEvents};}
function recordType(value){if(value&&value.recordType)return value.recordType;if(value&&[1,3,4].includes(value.schemaVersion))return "snapshot";if(value&&value.schemaVersion===5&&value.type==="method-call")return "method-trace";if(value&&(value.type==="configuration-change"||value.type==="configuration-change-rejected"))return "configuration-change";return "unknown";}
function normalize(value){
  if(value.schemaVersion===1)return {schemaVersion:1,agent:{name:"MadLava",version:value.agentVersion,configurationHash:value.configurationHash},runtime:{processId:value.pid,uptimeMillis:value.uptimeMillis},snapshot:{sequence:value.sequence||0,final:value.final===true||value.reason==="shutdown"},features:value.features||{},data:{configuration:value.configuration,effectiveConfiguration:value.effectiveConfiguration,capabilities:value.capabilities,cumulative:value.cumulative||{},sparkRuntime:value.sparkRuntime,reason:value.reason},raw:value};
  if(value.schemaVersion===3)return value;
  return {schemaVersion:4,agent:{name:"MadLava",version:value.agentVersion,configurationHash:value.configurationHash},runtime:{processId:value.pid,uptimeMillis:value.uptimeMillis},snapshot:{sequence:value.sequence||0,final:value.final===true||value.reason==="shutdown"},features:value.features||{},data:{effectiveConfiguration:value.effectiveConfiguration,reason:value.reason},raw:value};
}
function populateSnapshots(){selector.replaceChildren();report.forEach((value,index)=>{const option=document.createElement("option");option.value=String(index);option.textContent=`#${value.snapshot&&value.snapshot.sequence||index+1}${value.snapshot&&value.snapshot.final?" (final)":""}`;selector.appendChild(option);});selector.value=String(report.length-1);}
function selected(){return report[Number(selector.value)||0];}
function render(index){selector.value=String(index);const value=report[index],snap=value.snapshot||{};$("snapshot-count").textContent=String(report.length);$("agent-version").textContent=String(value.agent&&value.agent.version||"unknown");$("last-sequence").textContent=String(snap.sequence||index+1);$("final-state").textContent=snap.final?"yes":"no";$("drop-count").textContent=String(snap.droppedSnapshots||value.droppedSnapshots||0);renderFeatures(value);renderDiagnostics(value);$("raw").textContent=JSON.stringify(value,null,2);}
function renderFeatures(value){const body=$("features"),needle=filter.value.trim().toLowerCase(),entries=Object.entries(value.features||{}).filter(([name,item])=>`${name} ${item&&item.state||""}`.toLowerCase().includes(needle));body.replaceChildren();let healthy=0;entries.forEach(([name,item])=>{item=item||{};const state=String(item.state||"UNAVAILABLE");if(state==="RUNNING"||state==="AVAILABLE")healthy++;const accuracy=item.accuracy&&item.accuracy.level||item.accuracy||"UNAVAILABLE",reason=item.reason||item.availability||item.limitations||"-",row=document.createElement("tr");row.dataset.state=state;[name,state,accuracy,reason].forEach(text=>{const cell=document.createElement("td");cell.textContent=String(text);row.appendChild(cell);});body.appendChild(row);});$("health-count").textContent=String(healthy);$("empty-features").hidden=entries.length!==0;}
function reportQualityWarnings(value){const snapshot=value.snapshot||{},rawDropped=value.raw&&value.raw.droppedSnapshots,dropped=Number(snapshot.droppedSnapshots??value.droppedSnapshots??rawDropped??0),warningLevels=new Set(["APPROXIMATE","PARTIAL","DEGRADED","UNAVAILABLE","UNKNOWN"]),accuracyWarnings=Object.entries(value.features||{}).filter(([,item])=>{const accuracy=item&&item.accuracy,level=String(accuracy&&accuracy.level||accuracy||"").toUpperCase();return warningLevels.has(level);}).map(([name,item])=>{const accuracy=item&&item.accuracy,level=String(accuracy&&accuracy.level||accuracy||"UNKNOWN").toUpperCase();return `${name}: ${level}`;});return {dropped:Number.isFinite(dropped)?dropped:0,accuracyWarnings};}
function renderDiagnostics(value){const root=$("diagnostics");root.replaceChildren();const data=value.data||{},cumulative=data.cumulative||{},items=[],quality=reportQualityWarnings(value);if(quality.dropped>0||quality.accuracyWarnings.length)items.push(["Data quality",quality.dropped>0?`${quality.dropped} dropped snapshot(s)`:"No dropped snapshots",quality.accuracyWarnings.length?quality.accuracyWarnings.join(", "):"No declared accuracy warnings"]);const heap=data.heapUsage||cumulative.heapUsage,threads=data.threadStatistics||cumulative.threadStatistics,gc=data.garbageCollection||cumulative.garbageCollection,spark=data.spark||cumulative.spark;if(heap)items.push(["Heap",formatBytes(heap.used??heap.usedBytes),formatBytes(heap.max??heap.maxBytes)]);if(threads)items.push(["Threads",threads.live??threads.threadCount??"-",`peak ${threads.peak??threads.peakThreadCount??"-"}`]);if(gc)items.push(["Garbage collection",gc.count??"-",`${gc.timeMillis??"-"} ms`]);if(spark)items.push(["Spark",spark.compatibility&&spark.compatibility.state||spark.state||"UNAVAILABLE",spark.compatibility&&spark.compatibility.sparkVersion||spark.sparkVersion||"version unknown"]);if(!items.length)items.push(["Snapshot data","Available",`${Object.keys(data).length} data section(s)`]);items.forEach(parts=>{const card=document.createElement("article");parts.forEach((part,index)=>{const node=document.createElement(index===0?"h3":"p");node.textContent=String(part);card.appendChild(node);});root.appendChild(card);});}
function summary(value){return {source:sourceName,schemaVersion:value.schemaVersion,agent:value.agent,snapshot:value.snapshot,features:value.features,eventCount:events.length,diagnosticSections:Object.keys(value.data||{})};}
function formatBytes(value){if(!Number.isFinite(Number(value)))return "-";const units=["B","KiB","MiB","GiB"];let n=Number(value),i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return `${n.toFixed(i?1:0)} ${units[i]}`;}
